CREATE TABLE IF NOT EXISTS car (
  id SERIAL PRIMARY KEY,
  make CHARACTER VARYING NOT NULL,
  model CHARACTER VARYING NOT NULL,
  id_engine INTEGER NOT NULL,
  price NUMERIC
);

CREATE TABLE IF NOT EXISTS engine (
  id SERIAL PRIMARY KEY,
  displacement NUMERIC,
  power NUMERIC
);

ALTER TABLE car ADD FOREIGN KEY (id_engine) REFERENCES engine (id);